name: User Input Test

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Enter your name"
        required: true
        #default: " "
      message:
        description: "Enter a message"
        required: true
        #default: "Hello DevOps"
      type:
        description: "enter the env"
        required: true
jobs:
  print-inputs:
    runs-on: ubuntu-latest

    env:
      USER_NAME: ${{ github.event.inputs.username }}
      USER_MESSAGE: ${{ github.event.inputs.message }}
      USER_ENV: ${{ github.event.inputs.type }}

    steps:
      - name: Print User Inputs
        run: |
          echo "User Name: $USER_NAME"
          echo "User Message: $USER_MESSAGE"